# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["kailan@enviark.com"]
description = ""
language = "rust"
manifest_version = 2
name = "esi_example_app"
service_id = "7Oyrwb6dUr5ISWCcDess2Z"

[local_server]

  [local_server.backends]

    [local_server.backends."esi-test.edgecompute.app"]
      url = "https://esi-test.edgecompute.app"

    [local_server.backends."mock-s3.edgecompute.app"]
      url = "https://mock-s3.edgecompute.app"

    [local_server.backends."127.0.0.1"]
      url = "http://127.0.0.1"

    [local_server.backends."httpbin.org"]
      url = "http://httpbin.org"

[setup]

  [setup.backends]

    [setup.backends."esi-test.edgecompute.app"]
      address = "esi-test.edgecompute.app"
      port = 443

    [setup.backends."mock-s3.edgecompute.app"]
      address = "mock-s3.edgecompute.app"
      port = 443
