[package]
name = "esi_fastly_example_app"
version = "0.2.0"
authors = ["Kailan Blanks <kailan@enviark.com>"]
edition = "2018"
publish = false

[dependencies]
fastly = "^0.8"
esi = { path = "../esi" }
esi_fastly = { path = "../esi_fastly" }
wasm-rs-async-executor = "0.9.0"
