[package]
name = "esi_fastly_example_app"
version = "0.1.0"
authors = ["Kailan Blanks <kailan@enviark.com>"]
edition = "2018"

[dependencies]
fastly = "^0.7"
esi = { path = "../esi" }
esi_fastly = { path = "../esi_fastly" }
